### ISSUE TITLE
Does not restore a non-VS tab

### ISSUE THREAD

**Issue by migig** [eamodio/SaveAllTheTabs#10]
I have some tabs open, which are not VS solution items. External files.

This addon does not restore them. I assume it only restores solution items.

Please consider adding this.

**Comment by toddsay** [comment]
+1

**Comment by eamodio** [comment]
@migig unfortunately the apis I am using to restore tabs is provided by VS itself. I'm sure there is a way to get this to work manually, but honestly it isn't a feature I would be willing to implement (as I rarely use VS these days). Sorry -- although I would be open to a PR implementing this :)
