### ISSUE TITLE
Cannot install on Microsoft Visual Studio Professional 2013 Even Though Detected

### ISSUE THREAD

**Issue by Soulzityr** [eamodio/SaveAllTheTabs#13]
1/17/2017. Tried to install plugin onto Microsoft Visual Studio Professional 2013. It does not install properly.

![saveallthetabs](https://cloud.githubusercontent.com/assets/13813287/22033519/cc3f925e-dcb6-11e6-98eb-2651b99c5631.PNG)

**Comment by toddsay** [comment]
@eamodio: I'm thinking the issue here is that the current release targets "Microsoft.VisualStudio.Community" rather than "Microsoft.VisualStudio.Pro". It may be that "Pro" will work for both scenarios but I have not confirmed that.

**Comment by ksob72** [comment]
Having nearly the same issue.

1/25/2017 7:53:27 AM - Searching for applicable products...
1/25/2017 7:53:27 AM - Found installed product - Microsoft Visual Studio Professional 2012
1/25/2017 7:53:27 AM - Found installed product - Microsoft Visual Studio 2012 Shell (Integrated)
1/25/2017 7:53:27 AM - Found installed product - Microsoft Visual Studio Premium 2013
1/25/2017 7:53:27 AM - Found installed product - Microsoft Visual Studio Professional 2013
1/25/2017 7:53:27 AM - Found installed product - Microsoft Visual Studio 2013 Shell (Integrated)
1/25/2017 7:53:27 AM - Found installed product - Global Location
1/25/2017 7:53:27 AM - VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products.
   at VSIXInstaller.App.InitializeInstall()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()

**Comment by Soulzityr** [comment]
This just worked for me on a separate computer. Had both Microsoft Professional 2013 and Microsoft Community 2015.
